### ISSUE TITLE
"Error: BacnetError - Class:5 - Code:67"

### ISSUE THREAD

**Issue by tstockner** [BiancoRoyal/node-bacstack#1]
Node Version:12.16.1

Node BACstack Version: 0.0.1-beta.22

Hey together,

I am running the bacstack with a Siemens DXR2 Room Automation Device and I can greatly read all my data. 
But I can not write data. With the bacstack V0.0.1-beta.14 I always got the result "undefined" and I couldn't figure out what is the problem.
Now I receive "Error: BacnetError - Class:5 - Code:67" which is probably because of better error handling. Based on the handbook it is a "reject unrecognized Service" but no clue what to do with this message or where to search.

Also already had a look in here:
https://github.com/fh1ch/node-bacstack-browser/issues/2
But no help for me yet.

Anybody has Ideas on this?

Greets
Tom

**Comment by biancode** [comment]
@tstockner I had the same problem. It worked very well in early version and than it was broken. On a very first quick read inside the code it looks like there is now a routing inside which is not finished for all or not working well for every request type.
