### ISSUE TITLE
Issue on broadcast to 255.255.255.255

### ISSUE THREAD

**Issue by NubeDev** [BiancoRoyal/node-bacstack#15]
Node Version: `12`

Node BACstack Version: `0.1.1-beta.1`

- [x] Bug Report
- [ ] Feature Request
- [ ] Question

**Note:** Make sure you have read the [FAQs](https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md)
before logging this issue.

### Current Behaviour (Bug Report)
Not sending a read to correct BACnet device
-

### Expected Behaviour  (Bug Report)
Send bacnet read to correct device not broadcast on 255.255.255.255
-

### Steps to reproduce Issue  (Bug Report)

![image](https://user-images.githubusercontent.com/18637436/82436639-7d5c4080-9ad9-11ea-86e4-c9713e80deb5.png)

-

```javascript
// issue is that the destination is 255.255.255.255
// my host is 192.168.0.22
// target device is  192.168.0.201

const bacnet = require('./index');
const options = {
    deviceId: 1234,
    apduTimeout: 6000,

    };
const client = new bacnet({options, port: 47808, interface: '192.168.0.22', broadcastAddress: '255.255.255.255'});

// tried with and without the broadcastAddress
// const client = new bacnet({options, port: 47808, interface: '192.168.0.22'});


// Read Device Object
const requestArray = [{
  objectId: {type: 1, instance: 1},
  properties: [{id: 85}]
}];
client.readPropertyMultiple('192.168.0.201', requestArray, (err, value) => {
  console.log('value: ', JSON.stringify(value));
});
```

**Comment by NubeDev** [comment]
See maybe a fix but not sure as i dont undersand BACnet Virtual Link Layer `BVLL` 
https://github.com/NubeDev/node-bacstack/blob/master/lib/client.js#L1504

Also will you take pull requests? As the repo is locked

**Comment by biancode** [comment]
@NubeDev we work on this to collect all contribs from all existing repos. All PR's from the origin are merged here and we are happy about new PR's ;)

**Comment by NubeDev** [comment]
Thanks for the comment back. Do you know if that is an issue or was i doing soming wrong with setting up my BACnet client?

Ok so send PRs to this repo https://github.com/BiancoRoyal/node-bacstack?
As like I said before PRs are denied
```
fatal: unable to access 'https://github.com/BiancoRoyal/node-bacstack.git/': The requested URL returned error: 403
> git push -u origin broadcast-issue
remote: Permission to BiancoRoyal/node-bacstack.git denied to NubeDev.
```

**Comment by biancode** [comment]
@NubeDev please send a pull request as expected - you try to push directly - give us a chance to review your contributions and make a fork here, do your changes on your fork and send a pull request to the develop branch from your fork to this repo, please. We provide a [CONTRIBUTION](https://github.com/BiancoRoyal/node-bacstack/blob/master/CONTRIBUTING.md) information ;)

**Comment by biancode** [comment]
Please, watch the [Introduction](https://www.loom.com/share/e83de7c1bb0147deb6ce8792ab9f1c04)

**Comment by Apollon77** [comment]
> https://github.com/NubeDev/node-bacstack/blob/master/lib/client.js#L1504

This fix indeed does the job, but I think the best sosution need to be a different one. In fact when you give an IP then it should send a unicase and so needs to encode like in the second "if" case. So maybe we add a "typeof receiver === 'string'" check before the logic in this method to handle the case that an IP is given directly and convert it into the objects style 

```
reciever = {address: receiver}
```

**Comment by Apollon77** [comment]
I will add the fix into my commits I currently prepare
