### ISSUE TITLE
Read/Write values to a "virtual device" with a 4-byte mac address.

### ISSUE THREAD

**Issue by augster** [BiancoRoyal/node-bacstack#35]
Node Version: `16.3.0`

Node BACstack Version: `0.2.4`

- [ ] Bug Report
- [ ] Feature Request
- [X] Question

**Note:** Make sure you have read the [FAQs](https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md)
before logging this issue.

### Feature Request / Question
I'm trying to communicate with a "virtual" device that contains a 4-byte MAC address as seen in the attached Wireshark capture. I can see the devices perfectly fine in YABE, but I cannot discover these devices during a whoIs and haven't been successful with readProperty either.

![virtualDeviceMacLength](https://user-images.githubusercontent.com/6400730/127553309-5653d6be-6326-488b-a7f0-566bf916a864.png)

**Comment by nickngsr** [comment]
You could try using the below to whoIs for all networks
```javascript
client.whoIs({net: 0xFFFF})
```

and for that specific device you could try

``` javascript
client.readProperty({address: '172.22.102.39', net: 3373, adr: [129, 150, 152, 0]}, {type: 8, instance: 71312}, 77, (err, val) => {console.log(val)})
```

the adr may be wrong on that, i have assumed it is the 4 byte mac

**Comment by augster** [comment]
> You could try using the below to whoIs for all networks
> 
> ```js
> client.whoIs({net: 0xFFFF})
> ```
> 
> and for that specific device you could try
> 
> ```js
> client.readProperty({address: '172.22.102.39', net: 3373, adr: [129, 150, 152, 0]}, {type: 8, instance: 71312}, 77, (err, val) => {console.log(val)})
> ```
> 
> the adr may be wrong on that, i have assumed it is the 4 byte mac

This worked perfectly! Thanks a bunch.
