### ISSUE TITLE
Issues when getting Protocol_Object_Types_Supported in device object type

### ISSUE THREAD

**Issue by bgeaney** [BiancoRoyal/node-bacstack#41]
Node Version: `20.2.0`

Node BACstack Version: `0.2.4`

- [ ] Bug Report
- [ ] Feature Request
- [ x] Question

**Note:** Make sure you have read the [FAQs](https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md
)
before logging this issue.

### Feature Request / Question
I'm getting Protocol_Object_Types_Supported (BACnetObjectTypesSupported) using readPropertyMultiple, the returned values I get are {  value: [ 0, 1, 0, 0, 0, 0, 0, 1 ],  bitsUsed: 60} when I drill down to them. However this does not cover all possible values for each as per ASHRAE 135-2020, in this there are 63 possible values. 
When I monitor the value coming in over wireshark using YABE to check its represented as "protocol-object-types-supported: (Bit String) (FFFFFFFFTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTFFF)" with the T's representing Device and Network which is what I expect to see.
Do I need to do something with the returning value to have it match up?
Please ignore my ignorance if I'm missing something obvious.
-

### Current Behaviour (Bug Report)

-

### Expected Behaviour  (Bug Report)

-

### Steps to reproduce Issue  (Bug Report)

-

**Comment by Apollon77** [comment]
Cna you pleas epost a debug log of such a incoming message ?

**Comment by bgeaney** [comment]
Requirement changed so not needed. Meant to close earlier
